services:
  backend:
    build:
      context: ./backend
    ports:
      - "5038:5038"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: 2G
