services:
  api:
    build:
      context: ./api
    ports:
      - "5038:5038"
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  app:
    build:
      context: ./app
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0 --poll 2000
