version: "3.8"

services:
  api:
    build:
      context: ./api
    ports:
      - "5038:5038"
    environment:
      - NODE_ENV=production

  app:
    build:
      context: ./app
    ports:
      - "4200:4200"
    depends_on:
      - api
