services:
  backend:
    build:
      context: ./backend
    ports:
      - "5038:5038"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/logs:/usr/src/app/logs
      - /usr/src/app/node_modules
      - /usr/src/app/dist

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: 2G
