services:
  backend:
    build:
      context: ./backend
    ports:
      - "5038:5038"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ng serve --host 0.0.0.0 --poll 2000
